package it.portaleSTI.DTO;

// default package
// Generated 15-feb-2017 9.30.19 by Hibernate Tools 3.4.0.CR1

/**
 * Utentedto generated by hbm2java
 */
public class UtenteDTO {

	private int id;
	private String user;
	private String passw;
	private String nominativo;
	private String nome;
	private String cognome;
	private String indirizzo;
	private String comune;
	private String cap;
	private String EMail;
	private String telefono;
	private int idCompany;
	private String tipoutente;

	public UtenteDTO() {
	}


	public UtenteDTO(int id, String user, String passw, String nominativo,
			String nome, String cognome, String indirizzo, String comune,
			String cap, String EMail, String telefono, int idCompany,
			String tipoutente) {
		this.id = id;
		this.user = user;
		this.passw = passw;
		this.nominativo = nominativo;
		this.nome = nome;
		this.cognome = cognome;
		this.indirizzo = indirizzo;
		this.comune = comune;
		this.cap = cap;
		this.EMail = EMail;
		this.telefono = telefono;
		this.idCompany = idCompany;
		this.tipoutente = tipoutente;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getPassw() {
		return this.passw;
	}

	public void setPassw(String passw) {
		this.passw = passw;
	}

	public String getNominativo() {
		return this.nominativo;
	}

	public void setNominativo(String nominativo) {
		this.nominativo = nominativo;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	public String getIndirizzo() {
		return this.indirizzo;
	}

	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	public String getComune() {
		return this.comune;
	}

	public void setComune(String comune) {
		this.comune = comune;
	}

	public String getCap() {
		return this.cap;
	}

	public void setCap(String cap) {
		this.cap = cap;
	}

	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public int getIdCompany() {
		return this.idCompany;
	}

	public void setIdCompany(int idCompany) {
		this.idCompany = idCompany;
	}

	public String getTipoutente() {
		return this.tipoutente;
	}

	public void setTipoutente(String tipoutente) {
		this.tipoutente = tipoutente;
	}

}
