package it.portaleSTI.Util;

public class CostantiRelazione {
	
	
	// ---- COSTANTI RELAZIONE CAMPIONAMENTO
	public static final String CLIENTEPLACEHOLDER = "CLIENTEPLACEHOLDER";
	public static final String SEDEPLACEHOLDER = "SEDEPLACEHOLDER";
	public static final String CODICECOMMESSAPLACEHOLDER = "CODICECOMMESSAPLACEHOLDER";
	public static final String NOMEFILEPLACEHOLDER = "NOMEFILEPLACEHOLDER";
	public static final String DATEPRELIEVIPLACEHOLDER = "DATEPRELIEVIPLACEHOLDER";
	public static final String NOTESTABILIMENTOPLACEHOLDER = "NOTESTABILIMENTOPLACEHOLDER";
	public static final String LABORATORIOPLACEHOLDER = "LABORATORIOPLACEHOLDER";
	
	public static final String SOCIETAPLACEHOLDER = "SOCIETAPLACEHOLDER";
	public static final String CVOPERATOREPLACEHOLER = "CVOPERATOREPLACEHOLER";
	//public static final String OPERATOREPLACEHOLDER = "OPERATOREPLACEHOLDER";
	public static final String DOTAZIONIPLACEHOLDER = "DOTAZIONIPLACEHOLDER";
		//public static final String PUNTICAMPIONAMENTOPLACEHOLDER = "PUNTICAMPIONAMENTOPLACEHOLDER";
	public static final String SCHEDECAMPIONAMENTOPLACEHOLDER = "SCHEDECAMPIONAMENTOPLACEHOLDER";
	public static final String CONCLUSIONIPLACEHOLDER = "CONCLUSIONIPLACEHOLDER";
	
	public static final String RELAZIONEPLACEHOLDER = "RELAZIONEPLACEHOLDER";
	public static final String RELAZIONELABPLACEHOLDER = "RELAZIONELABPLACEHOLDER";
}
