# LOG4J configuration
log4j.rootLogger=ERROR, Appender1,Appender2

# Console
log4j.appender.Appender1=org.apache.log4j.ConsoleAppender
log4j.appender.Appender1.layout=org.apache.log4j.PatternLayout
log4j.appender.Appender1.layout.ConversionPattern=%-7p %d [%t] %c %x - %m%n


################################################
# LOG GENERALE - ROTAZIONE GIORNALIERA
################################################

log4j.appender.Appender2=org.apache.log4j.DailyRollingFileAppender
log4j.appender.Appender2.File=c:/Log/status.log
log4j.appender.Appender2.Append=true
log4j.appender.Appender2.DatePattern='.'yyyy-MM-dd
log4j.appender.Appender2.layout=org.apache.log4j.PatternLayout
log4j.appender.Appender2.layout.ConversionPattern=%-7p %d [%t] %c %x - %m%n


################################################
# LOG GESTIONE RILIEVI - ROTAZIONE GIORNALIERA
################################################

log4j.appender.GESTIONE_RILIEVI=org.apache.log4j.DailyRollingFileAppender

# File corrente
log4j.appender.GESTIONE_RILIEVI.File=c:/Log/gestione_rilievi.log

# In caso di riavvio Tomcat continua ad appendere
log4j.appender.GESTIONE_RILIEVI.Append=true

# Rotazione giornaliera
# Esempio: gestione_rilievi.log.2026-09-25
log4j.appender.GESTIONE_RILIEVI.DatePattern='.'yyyy-MM-dd
log4j.appender.GESTIONE_RILIEVI.layout=org.apache.log4j.PatternLayout
log4j.appender.GESTIONE_RILIEVI.layout.ConversionPattern=%-7p %d [%t] %c - %m%n


# Logger di classe
log4j.logger.it.portaleSTI.action.GestioneRilievi=INFO, GESTIONE_RILIEVI
log4j.additivity.it.portaleSTI.action.GestioneRilievi=false